import { ProviderInfo } from '../models/llm.model';

/** Registry of all supported LLM providers */
export const PROVIDERS: ProviderInfo[] = [
    {
        id: 'google',
        name: 'Google Gemini',
        icon: '✦',
        color: '#4285f4',
        apiKeyUrl: 'https://aistudio.google.com/apikey',
        apiKeyLabel: 'Google AI Studio',
        baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
        provider: 'gemini',
        chatModels: [
            'gemini-2.5-flash',
            'gemini-2.5-pro',
            'gemini-2.0-flash',
            'gemini-2.0-flash-lite',
            'gemini-1.5-pro',
            'gemini-1.5-flash',
        ],
        embeddingModels: ['text-embedding-004', 'embedding-001'],
        description: 'Бесплатный тариф с лимитами. Поддержка мультимодальности.',
    },
    {
        id: 'openai',
        name: 'OpenAI',
        icon: '◉',
        color: '#10a37f',
        apiKeyUrl: 'https://platform.openai.com/api-keys',
        apiKeyLabel: 'OpenAI Platform',
        baseUrl: 'https://api.openai.com/v1',
        provider: 'openai',
        chatModels: [
            'gpt-4.1',
            'gpt-4.1-mini',
            'gpt-4.1-nano',
            'gpt-4o',
            'gpt-4o-mini',
            'o3',
            'o3-mini',
            'o4-mini',
        ],
        embeddingModels: [
            'text-embedding-3-large',
            'text-embedding-3-small',
            'text-embedding-ada-002',
        ],
        description: 'Платные модели. Требуется пополнение баланса.',
    },
    {
        id: 'anthropic',
        name: 'Anthropic Claude',
        icon: '◈',
        color: '#d97706',
        apiKeyUrl: 'https://console.anthropic.com/settings/keys',
        apiKeyLabel: 'Anthropic Console',
        baseUrl: 'https://api.anthropic.com/v1',
        provider: 'openai',
        chatModels: [
            'claude-sonnet-4-20250514',
            'claude-opus-4-20250514',
            'claude-3.7-sonnet',
            'claude-3.5-sonnet-20241022',
            'claude-3.5-haiku-20241022',
            'claude-3-opus-20240229',
        ],
        embeddingModels: [],
        description: 'Мощные модели для кода. Claude Opus — топ-класс. Требует прокси/OpenRouter для OpenAI-формата.',
    },
    {
        id: 'openrouter',
        name: 'OpenRouter',
        icon: '⬡',
        color: '#6366f1',
        apiKeyUrl: 'https://openrouter.ai/keys',
        apiKeyLabel: 'OpenRouter Dashboard',
        baseUrl: 'https://openrouter.ai/api/v1',
        provider: 'openai',
        chatModels: [
            'anthropic/claude-sonnet-4',
            'anthropic/claude-opus-4',
            'anthropic/claude-3.7-sonnet',
            'openai/gpt-4.1',
            'openai/o3',
            'google/gemini-2.5-pro',
            'google/gemini-2.5-flash',
            'deepseek/deepseek-r1',
            'deepseek/deepseek-chat-v3-0324',
            'meta-llama/llama-4-maverick',
            'mistralai/mistral-large-latest',
        ],
        embeddingModels: [],
        description: 'Единый API ко всем провайдерам. Поддержка Claude, GPT, Gemini и др. через OpenAI-формат.',
    },
    {
        id: 'groq',
        name: 'Groq',
        icon: '⚡',
        color: '#f97316',
        apiKeyUrl: 'https://console.groq.com/keys',
        apiKeyLabel: 'Groq Console',
        baseUrl: 'https://api.groq.com/openai/v1',
        provider: 'openai',
        chatModels: [
            'llama-3.3-70b-versatile',
            'llama-3.1-8b-instant',
            'mixtral-8x7b-32768',
            'gemma2-9b-it',
        ],
        embeddingModels: [],
        description: 'Бесплатные модели с ультра-быстрой генерацией (LPU).',
    },
    {
        id: 'mistral',
        name: 'Mistral AI',
        icon: '▲',
        color: '#ff7000',
        apiKeyUrl: 'https://console.mistral.ai/api-keys',
        apiKeyLabel: 'Mistral Console',
        baseUrl: 'https://api.mistral.ai/v1',
        provider: 'openai',
        chatModels: [
            'mistral-large-latest',
            'mistral-medium-latest',
            'mistral-small-latest',
            'codestral-latest',
            'open-mistral-nemo',
        ],
        embeddingModels: ['mistral-embed'],
        description: 'Европейские модели. Codestral — модель для кода.',
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        icon: '◆',
        color: '#2563eb',
        apiKeyUrl: 'https://platform.deepseek.com/api_keys',
        apiKeyLabel: 'DeepSeek Platform',
        baseUrl: 'https://api.deepseek.com/v1',
        provider: 'openai',
        chatModels: [
            'deepseek-chat',
            'deepseek-reasoner',
        ],
        embeddingModels: [],
        description: 'Модели с рассуждением. Очень дёшево.',
    },
    {
        id: 'ollama',
        name: 'Ollama (локальный)',
        icon: '🦙',
        color: '#a855f7',
        apiKeyUrl: 'https://ollama.com/download',
        apiKeyLabel: 'Скачать Ollama',
        baseUrl: 'http://localhost:11434/v1',
        provider: 'openai',
        chatModels: [
            'llama3.3',
            'llama3.1',
            'qwen2.5-coder',
            'codellama',
            'mistral',
            'gemma2',
            'phi3',
        ],
        embeddingModels: [
            'nomic-embed-text',
            'mxbai-embed-large',
            'all-minilm',
        ],
        description: 'Запуск моделей на своём ПК. Бесплатно, приватно. API ключ не нужен.',
    },
    {
        id: 'lmstudio',
        name: 'LM Studio (локальный)',
        icon: '🖥',
        color: '#06b6d4',
        apiKeyUrl: 'https://lmstudio.ai/',
        apiKeyLabel: 'Скачать LM Studio',
        baseUrl: 'http://localhost:1234/v1',
        provider: 'openai',
        chatModels: ['openai/gpt-oss-20b', 'local-model'],
        embeddingModels: ['text-embedding-mxbai-embed-large-v1', 'local-embedding-model'],
        description: 'GUI для запуска моделей локально. API ключ не нужен.',
    },
];

/** Providers that have embedding models */
export const EMBEDDING_PROVIDERS = PROVIDERS.filter(p => p.embeddingModels.length > 0);

/** Find provider by id */
export function getProviderById(id: string): ProviderInfo | undefined {
    return PROVIDERS.find(p => p.id === id);
}
